name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Compilar, probar y generar artefacto Java
        run: |
          echo "===  Checkout del cÃ³digo ==="
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY repo
          cd repo

          echo "===  Configurando Java 17 ==="
          sudo apt update -y
          sudo apt install -y openjdk-17-jdk

          echo "===  Compilando y ejecutando tests ==="
          cd src
          javac *.java
          java -ea CalculadoraTest

          echo "===  Creando ejecutable ==="
          jar cfe ../calculadora.jar Main *.class

          echo "===  Proceso completado ==="
        shell: bash

      - name: ðŸ“¤ Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-ejecutable
          path: calculadora.jar
